- name: "Delete users"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Create User"
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'present'
        shell: '/bin/bash'
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: 'on_create'
      when: user_create == 'yes'
    - name: "Delete users"
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'absent'
        remove: true
      when: user_create == 'no'
