- name: "Manage users"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Create User"
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'present'
        shell: '/bin/bash'
      when: user_create == 'yes'

    - name: "Allow SSH Authentication via key for vagrant account to new remote account"
      authorized_key:
        user: "{{ user_account | default('ansible') }}"
        state: 'present'
        manage_dir: true
        key: "{{ lookup('file', '/home/vagrant/.ssh/id_ecdsa.pub') }}"
      when: user_create == 'yes'

    - name: "Delete users"
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'absent'
        remove: true
      when: user_create == 'no'
