- name: "Create and Manage users"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Create a user account"
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'present'
        shell: '/bin/bash'

