---
# tasks file for mysql
# MySQL Configuration
    - name: Install db package
      package:
        name:
          - mariadb-server
          - python3-mysqlclient
        update_cache: true 
        state: present
    - name: start mysql
      service:
        name: mariadb
        state: started
        enabled: true 
    - name: create a new database
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        collation: utf8_general_ci

    - name: create a database user
      mysql_user:
        name: "{{ mysql_db_user }}"
        password: "{{ mysql_db_user_pass }}"
        priv: "{{ mysql_db_user_priv }}"
        host: "{{ mysql_db_allowed_hosts }}"
        state: present

    - name: allow localhost
      mysql_user:
        name: "{{ mysql_db_user }}"
        password: "{{ mysql_db_user_pass }}"
        priv: "{{ mysql_db_user_priv }}"
        host: localhost
        state: present

    - name: copy sample data
      copy:
        src: demo.sql
        dest: /tmp/demo.sql

    - name: insert sample data
      shell: cat /tmp/demo.sql | mysql -u demo -pdemo demo