- name: "Create a Virtual data Optimizer"
  hosts:
   - stream
   - aws
  become: true
  gather_facts: true
  tasks:
    - name: "Ensure Vdo Package is installed"
      package:
        name:
          - vdo
          - kmod-kvdo
          - kernel
        state: latest
        update_cache: true

    - name: "reboot remote hosts and wait for them to restart"
      reboot:
        msg: "Reboot initiated"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 20
        test_command: whoami
    
    - name: "Ensure Vdo service is Running and Enabled"
      service:
        name: vdo
        state: started
        enabled: true

    - name: "Create a VDO device vdo1 "
      vdo:
        name: 'vdo1'
        state: 'present'
        device: '/dev/sdb'
        logicalsize: "20G"

    - name: "formate the vdo device"
      filesystem:
        type: xfs
        dev: "/dev/mapper/vdo1"

    - name: "Create a mountpoint file"
      file:
        path: "/vdo1"
        state: "directory"

    - name: "mount the mountpoint file"
      mount:
        path: "/vdo1"
        fstype: xfs
        state: "mounted"
        src: "/dev/mapper/vdo1"
        opts: defaults,x-systemd.requires=vdo.service

