---
- name: "Install lamp stack on remote hosts"
  hosts: centos2
  become: true 
  roles:
    - apache
    - mysql
  tasks:
    - name: install script with db connectivity
      copy:
        src: db.php
        dest: "{{ apache_document_root_path }}db.php"
        mode: 0775

