- name: "Loop over list of writers"
  hosts: centos1
  vars:
    writers:
      - Tolstoy 
      - Dostoyevski
      - London
      - Sabahattin
      - Austen
  tasks:
    - name: Template loop example
      template:
        src: Templates/template.j2
        dest: /tmp/output-loop.txt







