---
# tasks file for ntp
- name: make sure chrony is installed on target hosts
  package:
    name:
      - chrony
    state: present
  
- name: ntp configuration 
  template:
    src: chrony.j2
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
  notify: restart chrony daemon
- name: set timezon
  timezone:
    name: "Europe/Istanbul"