- name: "Manage Local Account and generating a ssh key to our local user"
  hosts: 'rhel'
  become: true
  gather_facts: false
  tasks:
    - name: "Manage a user account"
      user:
        name: "{{ user_account }}"
        state: 'present'
        generate_ssh_key: true
        ssh_key_file: ".ssh/id_ecdsa"
        ssh_key_type: "ecdsa"

