- name: "Manage Local Account and generating a ssh key to our local user"
  hosts: 'rhel'
  become: true
  gather_facts: false
  tasks:
    - name: "Manage a user account"
      user:
        name: "vagrant"
        state: 'present'
        generate_ssh_key: true
        ssh_key_type: 'ecdsa'
        ssh_key_file: '.ssh/id_ecdsa'

          
- name: "Manage Users"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Create User Account, SSH Auth and Sudoers Entry"
      block:
        - name: "Create User"
          user:
            name: "ansible"
            state: 'present'
            shell: '/bin/bash'
            password: "{{ 'Password1' | password_hash('sha512') }}"
            update_password: 'on_create'
        - name: "Allow SSH Authentication"
          authorized_key:
            user: "ansible"
            state: 'present'
            manage_dir: true
            key: "{{ lookup('file', '/home/vagrant/.ssh/id_ecdsa.pub') }}"
        - name: "copy sudoers file"
          copy:
            dest: "/etc/sudoers.d/ansible"
            content: 'ansible ALL=(root) NOPASSWD: ALL'    
      when: user_create == 'yes'

    - name: "Delete users"
      user:
        name: "ansible"
        state: 'absent'
        remove: true
      when: user_create == 'no'
