- name: Archiving
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Create a backup folder
      file:
        path: '/backup'
        state: 'directory'
        owner: automation
        group: automation
        mode: 0755
        
- name: Archive config files
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create a folder for archive      
      file:
        path: /backup
        owner: automation
        group: automation
        state: directory
        mode: 0755

- name: create the archive
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create the archive
      archive:
        path: /etc
        dest: /backup/configuration.gz
        format: gz
        owner: automation
        group: automation
        mode: 0660

- name: fetch the archive
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Retrieves archives from managed nodes
      fetch:
        src: /backup/configuration.gz
        dest: /backup/{{ ansible_hostname }}-configuration.gz
        owner: automation
        group: automation
        mode: 0660

