- name: configure a centeral repo for all remote hosts for package installation
  hosts: 
  - proxy
  - database
  - webservers
  become: yes
  gather_facts: false
  tasks:
    - name: copy /etc/hosts to remote hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        
    - name: configure BaseOS repo
      yum_repository:
        name: baseOS
        description: http://repo.ansi.example.com
        baseurl: http://192.168.55.199
        gpgcheck: no
        enabled: yes

    - name: configure AppStream repo
      yum_repository:
        name: AppStream
        description: http://repo.ansi.example.com
        baseurl: http://192.168.55.199
        gpgcheck: no
        enabled: yes

- name: configure a centeral repo for all remote hosts for package installation
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: copy /etc/hosts to remote hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        
    - name: configure BaseOS repo
      yum_repository:
        name: baseOS
        description: http://repo.ansi.example.com
        baseurl: http://192.168.55.199
        gpgcheck: no
        enabled: yes

    - name: configure AppStream repo
      yum_repository:
        name: AppStream
        description: http://repo.ansi.example.com
        baseurl: http://192.168.55.199
        gpgcheck: no
        enabled: yes
