- name: Changing MOTD
  hosts: all
  become: yes
  tasks:
  - name: Copy the content to HAProxy
    copy:
      content: "Welcome to HAProxy server\n"
      dest: /etc/motd
    when: "inventory_hostname in groups['proxy']"
  - name: Copy the content to Apache
    copy:
      content: "Welcome to Apache server\n"
      dest: /etc/motd
    when: "inventory_hostname in groups['webservers']"
  - name: Copy the content to MySQL
    copy:
      content: "Welcome to MySQL server\n"
      dest: /etc/motd
    when: "inventory_hostname in groups['database']"
