- name: Configure SWAP
  hosts: database
  become: true
  gather_facts: false
  vars:
    vg: swap
    lv: swap
  tasks:
  # - name: Install tools
  #   yum:
  #     name: lvm2
  - name: Partition the drive
    parted:
      device: /dev/sdb
      part_type: primary
      label: msdos
      number: 2
      flags: [ lvm ]
      state: present
      unit: MB
      part_start: "60%"
      part_end: "100%"

  - name: Create volume group
    lvg:
      pvs: /dev/sdb2
      vg: "{{ vg }}"
      state: present

  - name: Create logical volume
    lvol:
      lv: "{{ lv }}"
      size: 100%VG
      vg: "{{ vg }}"
      state: present

  - name: Create filesystem
    filesystem:
      dev: /dev/{{ vg }}/{{ lv }}
      fstype: swap
  - name: Mount on boot
    lineinfile:
      line: "/dev/{{ vg }}/{{ lv }} swap swap defaults 0 0"
      path: /etc/fstab

  - name: Check if mounted
    shell: "lsblk -s | grep {{ vg }}-{{ lv }}"
    changed_when: false
    register: mounts

  - name: Mount if not mounted
    shell: swapon /dev/{{ vg }}/{{ lv }}
    when: "'[SWAP]' not in mounts.stdout"
